name: snaphunt
description: "An AI-driven scavenger hunt app built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.1.2
  geolocator: ^10.1.0
  permission_handler: ^12.0.1
  camera: ^0.11.2
  path_provider: ^2.1.2
  image_picker: ^1.1.1

  # Firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.1
  firebase_auth: ^4.19.0

  # Local storage / utils
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.1.0

  # Icons
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^2.5.2
  mocktail: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/person-circle.svg
    - assets/icons/book.svg
    - assets/icons/trophy-fill.svg
    - assets/icons/chevron-compact-left.svg
    - assets/icons/camera.svg
    - assets/icons/maps.svg
    - assets/icons/copy.svg
