// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBinQuDKqXeLrkUohZV2f0tzW9my1OiHdE',
    appId: '1:524135744410:android:a2148bfb6a0f9ea00d7023',
    messagingSenderId: '524135744410',
    projectId: 'snaphunt-d99b8',
    storageBucket: 'snaphunt-d99b8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuFaDiF0mLZigGFPTE_Sxf1CTt-ORUao',
    appId: '1:524135744410:web:4ac49d0a51d9b7190d7023',
    messagingSenderId: '524135744410',
    projectId: 'snaphunt-d99b8',
    authDomain: 'snaphunt-d99b8.firebaseapp.com',
    storageBucket: 'snaphunt-d99b8.firebasestorage.app',
    measurementId: 'G-0V33X5Z0NG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKLQveZ7h10Ree_TlQX7mOoKB9H3CJzpM',
    appId: '1:524135744410:ios:220c3170fa1d2f930d7023',
    messagingSenderId: '524135744410',
    projectId: 'snaphunt-d99b8',
    storageBucket: 'snaphunt-d99b8.firebasestorage.app',
    iosBundleId: 'com.example.snaphunt',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLQveZ7h10Ree_TlQX7mOoKB9H3CJzpM',
    appId: '1:524135744410:ios:220c3170fa1d2f930d7023',
    messagingSenderId: '524135744410',
    projectId: 'snaphunt-d99b8',
    storageBucket: 'snaphunt-d99b8.firebasestorage.app',
    iosBundleId: 'com.example.snaphunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLuFaDiF0mLZigGFPTE_Sxf1CTt-ORUao',
    appId: '1:524135744410:web:f6f3fa9637d6d6130d7023',
    messagingSenderId: '524135744410',
    projectId: 'snaphunt-d99b8',
    authDomain: 'snaphunt-d99b8.firebaseapp.com',
    storageBucket: 'snaphunt-d99b8.firebasestorage.app',
    measurementId: 'G-HYGSF5DBQS',
  );

}